language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
node_js:
  - "10"
sudo: required
notifications:
  email: false
cache:
  directories:
    - node_modules

before_install:
  # Enable user namespace cloning
  - "sysctl -w kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # yarn is outdated on Linux images
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - source ./scripts/retry.sh
  - retry 3 yarn install

script:
  - yarn lint
  - yarn build
  - yarn test
