os:
  - linux
language: node_js
node_js:
  - "10"
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

notifications:
  email: false

cache:
  directories:
    - node_modules

before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # yarn is outdated on Linux images
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
      export PATH=$HOME/.yarn/bin:$PATH
    fi

install:
  - source ./scripts/retry.sh
  - retry 3 yarn install

script:
  - yarn lint
  - yarn build
  - yarn test
